esphome:
  name: lilygo-tqt-climate
  friendly_name: LILYGO T-QT Pro Climate Complex

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  # level: VERBOSE

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret web_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LILYGO T-QT Pro Fallback"
    password: !secret ap_password

# Sync time with NTP
time:
  - platform: sntp
    id: sntp_time
    timezone: "Asia/Kolkata"

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_password

# I2C Configuration for AHT10
i2c:
  - id: bus_a
    sda: GPIO18
    scl: GPIO48
    scan: true
    frequency: 10000

  # I2C Configuration for BME280
  - id: bus_b
    sda: GPIO34
    scl: GPIO33
    scan: true
    frequency: 10000

# Sensors
sensor:
  # Temperature & Humidity Sensor AHT10
  - platform: aht10
    variant: AHT20
    i2c_id: bus_a
    temperature:
      name: "Air Temperature"
      accuracy_decimals: 2
      internal: false
      icon: "mdi:thermometer"
    humidity:
      name: "Humidity"
      accuracy_decimals: 0
      internal: false
      icon: "mdi:water-percent"
    update_interval: 10s

  # Hygrometer Analog Reading
  - platform: adc
    internal: false
    pin: GPIO17
    name: "Soil Moisture"
    update_interval: 10s
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 100.0

  # Rainwater Sensor
  - platform: adc
    internal: false
    pin: GPIO16
    name: "Rain Level"
    update_interval: 10s
    accuracy_decimals: 1
    icon: "mdi:weather-rainy"
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 100.0

  # BME280 Sensor
  - platform: bme280_i2c
    i2c_id: bus_b
    temperature:
      name: "BME280 Temperature"
      internal: false
      accuracy_decimals: 1
      icon: "mdi:thermometer"
    pressure:
      name: "BME280 Pressure"
      internal: false
      accuracy_decimals: 1
      icon: "mdi:gauge"
    humidity:
      name: "BME280 Humidity"
      internal: false
      accuracy_decimals: 1
      icon: "mdi:water-percent"
    # address: 0x77
    update_interval: 10s

binary_sensor:
  # Hygrometer Digital Output
  - platform: gpio
    pin: GPIO36
    name: "IR Sensor"
    icon: "mdi:water"
    device_class: moisture
